### ISSUE TITLE
Building and running units tests

### ISSUE THREAD

**Issue by object** [haf/Http.fs#98] opened 2016-07-27 08:14 UTC
I forked the repo, and there are a few things I am trying to figure out when building and running tests.
1. It complained about missing AssembleVersionInfo.fs (event after I ran the target Up) I had to copy AssemblyInfo.fs to AssemblyVersionInfo.fs, then it worked.
2. If I run then build.bat without a target, it goes quite far but eventually fail complaining about missing Prelude.fs.
3. I don't seem to be able to fail unit tests. I tried to fail the testCase "multipart/form-data with multipart/mixed" by entering some wrong data, but unit tests passed. The easiest is to change the name of the file in MultipartMixed form from "file1.txt" to "file123.txt". Then it should of course fail, but it doesn't! The build reports about 54 passed, 2 ignored and 0 failed tests. There must be something fundamentally wrong in what I am doing. I even double checked that I am running build in the right project. Yes I am.

**Comment by haf** [comment] 2016-07-27 11:00
Hi,
1. It uses [albacore](https://github.com/Albacore/albacore/#installing-ruby-on-windows) to create the assembly version infos.
2. You must be building a really old version which was split over many files; there's only a single file in the project: https://github.com/relentless/Http.fs/blob/master/HttpFs/HttpFs.fsproj#L50 – also have a look at the source tree - to facilitate source-code-dependencies if you want to use it that way.
3. This may be related to not being able to build. Let's start by fixing 1 and 2. The command to build once albacore is installed is `bundle exec rake`.

**Comment by object** [comment] 2016-07-27 12:33
After switching to Albacore it builds fine and I am able to fail unit test. Perhaps obsolete build files should be removed to avoid confusions like mine. But it builds now :)

**Comment by object** [comment] 2016-07-27 13:02
Oops, I guess I closed it too soon. It's an integration tests that failed, but unit tests still pass. I changed RequestBody.fs and specified wrong assertion in testCase "multipart/form-data with multipart/mixed", then ran "bundle exec rake test:unit", and it reported about 54 passed tests and none failed.

What I did in that testCase is replaced line

Assert.Equal("should have correct body", expected, subject)

with

Assert.Equal("should have correct body", "expected", subject)

I.e. wrapped "expected" in quotes which should have made test fail but it didn't.

Since UnitTest project is a self-testing application I ran it, but with the same result: it reported that 54 tests passed, 0 failed.

**Comment by object** [comment] 2016-07-27 13:04
Oh I see, it's skipped! This line:

if Type.GetType ("Mono.Runtime") = null then Tests.skiptest "random impl different on .Net"

I am on .NET, not Mono, so this test is not run.

**Comment by haf** [comment] 2016-07-27 18:14
I think Xamarin may have merged the .net Random implementation actually. So, can I do something for this issue?

**Comment by object** [comment] 2016-07-27 22:29
I don't know why these tests were originally ignored. I can re-enable them and see how it goes.

**Comment by object** [comment] 2016-07-28 08:24
I submitted PR on issue 97 that we discussed earlier. I see that appveyor server build fails with the error I encountered earlier, so this is something for you to check:

```
 1>FSC : error FS0225: Source file 'C:\projects\http-fs\HttpFs\AssemblyVersionInfo.fs' could not be found [C:\projects\http-fs\HttpFs\HttpFs.fsproj]
 1>Done Building Project "C:\projects\http-fs\HttpFs\HttpFs.fsproj" (Build target(s)) -- FAILED.
```

Build FAILED.

**Closed as completed** 2016-07-29 06:11 UTC

**Comment by haf** [comment] 2016-07-29 16:20
Hey @object  I think I've fixed the appveyor problem now.

**Comment by haf** [comment] 2016-07-29 16:54
Hmm... I can't reproduce this locally: https://ci.appveyor.com/project/GrantCrofton/http-fs/build/1.5.1.164#L221 – do you think you could try since you have Windows?

**Comment by object** [comment] 2016-07-29 17:56
That was my work machine, can't try right now. Will check this out on Monday.
